url: https://ucmercedgame.dev
baseurl: ""

# Site settings
title: Game Development Club at UC Merced
email: ucmgamedevelopmentclub@gmail.com
description: "The GDC@UC Merced focuses on game development, with members working on anything from programming to art. We are a club for UC Merced students who are interested in game dev, any level of experience is welcome.."
logo: /img/GDC_Logo.png
lang: en_US

social:
  name: 
  links:
    - https://discord.gg/ztyDgmP
    - https://www.facebook.com/groups/269175380309064/
    - https://ucmgdc.itch.io/
    - https://github.com/UCMercedGameDevelopmentClub
    - https://ucmerced.presence.io/organization/game-development-club

# Team names, titles and social links
people:
- name: Anooj Vadodkar
  position: President / Programming Chair

- name: Sean Rook
  position: Vice President

- name: Farid Mirzaei
  position: Secretary

- name: Kaylee Davis
  position: Treasurer

- name: Alex Guzman
  position: Events Coordinator / Writing Chair

- name: Derek Sollberger
  position: Advisor
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: discord
    url: https://discord.gg/ztyDgmP
  - title: facebook-f
    url: https://www.facebook.com/groups/269175380309064/
  - title: itch-io 
    url: https://ucmgdc.itch.io/
  - title: github
    url: https://github.com/UCMercedGameDevelopmentClub

# Postal address (add as many lines as necessary)
address:
  - line: 5200 N. Lake Dr
  - line: Merced, CA 95340

# Build settings
markdown: kramdown
permalink: pretty
future: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap