url: https://ucmercedgamedevelopmentclub.github.io
baseurl: /welcome

# Site settings
title: UC Merced Game Development Club
email: your-email@domain.com
description: "UC Merced's Game Development Club"


# Team names, titles and social links
people:
- name: Pat Dimaandal
  position: President / Visual Arts Chair

- name: Mark Armstrong
  position: Vice President

- name: Imani Jones
  position: Secretary

- name: Russell Yu
  position: Treasurer

- name: Andrew Wong
  position: Events Coordinator

- name: Justin Lok
  position: Programing Chair

- name: Charles Chung
  position: Events Coordinator / Programing Chair

- name: Nathan Huynh
  position: Sound Design Chair

- name: Anooj Vadodkar
  position: Writing Chair

- name: Derek Sollberger
  position: Advisor
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: discord
    url: http://discord.gg/5z6THuT
  - title: facebook
    url: https://www.facebook.com/groups/269175380309064/
  - title: itch-io 
    url: https://ucmgdc.itch.io/
  - title: github
    url: https://github.com/UCMercedGameDevelopmentClub

# Postal address (add as many lines as necessary)
address:
  - line: 5200 N. Lake Dr
  - line: Merced, CA 95340

# Build settings
markdown: kramdown
permalink: pretty