url: https://ucmercedgame.dev
baseurl: ""

# Site settings
title: UC Merced Game Development Club
email: ucmgamedevelopmentclub@gmail.com
description: "UCMGDC focuses on game development, all the way from coding to creating art. We are a club for UC Merced students who are interested in game dev."
logo: /img/GDC_Logo.png
lang: en_US

social:
  name: 
  links:
    - http://discord.gg/5z6THuT
    - https://www.facebook.com/groups/269175380309064/
    - https://ucmgdc.itch.io/
    - https://github.com/UCMercedGameDevelopmentClub
    - https://catlife.ucmerced.edu/organization/gdc

# Team names, titles and social links
people:
- name: Pat Dimaandal
  position: President / Visual Arts Chair

- name: Mark Armstrong
  position: Vice President

- name: Imani Jones
  position: Secretary

- name: Russell Yu
  position: Treasurer

- name: Andrew Wong
  position: Events Coordinator

- name: Justin Lok
  position: Programing Chair

- name: Charles Chung
  position: Events Coordinator / Programing Chair

- name: Nathan Huynh
  position: Sound Design Chair

- name: Anooj Vadodkar
  position: Writing Chair

- name: Derek Sollberger
  position: Advisor
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: discord
    url: http://discord.gg/5z6THuT
  - title: facebook-f
    url: https://www.facebook.com/groups/269175380309064/
  - title: itch-io 
    url: https://ucmgdc.itch.io/
  - title: github
    url: https://github.com/UCMercedGameDevelopmentClub

# Postal address (add as many lines as necessary)
address:
  - line: 5200 N. Lake Dr
  - line: Merced, CA 95340

# Build settings
markdown: kramdown
permalink: pretty
future: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap